export default {
  countries: [
    { flag: "af", value: "af", text: "Afghanistan                ", key: "af" },
    { flag: "ax", value: "ax", text: "Aland Islands              ", key: "ax" },
    { flag: "al", value: "al", text: "Albania                    ", key: "al" },
    { flag: "dz", value: "dz", text: "Algeria                    ", key: "dz" },
    { flag: "as", value: "as", text: "American Samoa             ", key: "as" },
    { flag: "ad", value: "ad", text: "Andorra                    ", key: "ad" },
    { flag: "ao", value: "ao", text: "Angola                     ", key: "ao" },
    { flag: "ai", value: "ai", text: "Anguilla                   ", key: "ai" },
    { flag: "ag", value: "ag", text: "Antigua                    ", key: "ag" },
    { flag: "ar", value: "ar", text: "Argentina                  ", key: "ar" },
    { flag: "am", value: "am", text: "Armenia                    ", key: "am" },
    { flag: "aw", value: "aw", text: "Aruba                      ", key: "aw" },
    { flag: "au", value: "au", text: "Australia                  ", key: "au" },
    { flag: "at", value: "at", text: "Austria                    ", key: "at" },
    { flag: "az", value: "az", text: "Azerbaijan                 ", key: "az" },
    { flag: "bs", value: "bs", text: "Bahamas                    ", key: "bs" },
    { flag: "bh", value: "bh", text: "Bahrain                    ", key: "bh" },
    { flag: "bd", value: "bd", text: "Bangladesh                 ", key: "bd" },
    { flag: "bb", value: "bb", text: "Barbados                   ", key: "bb" },
    { flag: "by", value: "by", text: "Belarus                    ", key: "by" },
    { flag: "be", value: "be", text: "Belgium                    ", key: "be" },
    { flag: "bz", value: "bz", text: "Belize                     ", key: "bz" },
    { flag: "bj", value: "bj", text: "Benin                      ", key: "bj" },
    { flag: "bm", value: "bm", text: "Bermuda                    ", key: "bm" },
    { flag: "bt", value: "bt", text: "Bhutan                     ", key: "bt" },
    { flag: "bo", value: "bo", text: "Bolivia                    ", key: "bo" },
    { flag: "ba", value: "ba", text: "Bosnia                     ", key: "ba" },
    { flag: "bw", value: "bw", text: "Botswana                   ", key: "bw" },
    { flag: "bv", value: "bv", text: "Bouvet Island              ", key: "bv" },
    { flag: "br", value: "br", text: "Brazil                     ", key: "br" },
    { flag: "vg", value: "vg", text: "British Virgin Islands     ", key: "vg" },
    { flag: "bn", value: "bn", text: "Brunei                     ", key: "bn" },
    { flag: "bg", value: "bg", text: "Bulgaria                   ", key: "bg" },
    { flag: "bf", value: "bf", text: "Burkina Faso               ", key: "bf" },
    {
      flag: "mm",
      value: "mm",
      text: "Burma                      ",
      key: "mm",
      alias: "Myanmar"
    },
    { flag: "bi", value: "bi", text: "Burundi                    ", key: "bi" },
    { flag: "tc", value: "tc", text: "Caicos Islands             ", key: "tc" },
    { flag: "kh", value: "kh", text: "Cambodia                   ", key: "kh" },
    { flag: "cm", value: "cm", text: "Cameroon                   ", key: "cm" },
    { flag: "ca", value: "ca", text: "Canada                     ", key: "ca" },
    { flag: "cv", value: "cv", text: "Cape Verde                 ", key: "cv" },
    { flag: "ky", value: "ky", text: "Cayman Islands             ", key: "ky" },
    { flag: "cf", value: "cf", text: "Central African Republic   ", key: "cf" },
    { flag: "td", value: "td", text: "Chad                       ", key: "td" },
    { flag: "cl", value: "cl", text: "Chile                      ", key: "cl" },
    { flag: "cn", value: "cn", text: "China                      ", key: "cn" },
    { flag: "cx", value: "cx", text: "Christmas Island           ", key: "cx" },
    { flag: "cc", value: "cc", text: "Cocos Islands              ", key: "cc" },
    { flag: "co", value: "co", text: "Colombia                   ", key: "co" },
    { flag: "km", value: "km", text: "Comoros                    ", key: "km" },
    { flag: "cd", value: "cd", text: "Congo                      ", key: "cd" },
    { flag: "cg", value: "cg", text: "Congo Brazzaville          ", key: "cg" },
    { flag: "ck", value: "ck", text: "Cook Islands               ", key: "ck" },
    { flag: "crc.svg", value: "crc.svg", text: "Costa Rica                 ", key: "crc.svg" },
    { flag: "ci", value: "ci", text: "Cote Divoire               ", key: "ci" },
    { flag: "hr", value: "hr", text: "Croatia                    ", key: "hr" },
    { flag: "cu", value: "cu", text: "Cuba                       ", key: "cu" },
    { flag: "cy", value: "cy", text: "Cyprus                     ", key: "cy" },
    { flag: "cz", value: "cz", text: "Czech Republic             ", key: "cz" },
    { flag: "dk", value: "dk", text: "Denmark                    ", key: "dk" },
    { flag: "dj", value: "dj", text: "Djibouti                   ", key: "dj" },
    { flag: "dm", value: "dm", text: "Dominica                   ", key: "dm" },
    { flag: "do", value: "do", text: "Dominican Republic         ", key: "do" },
    { flag: "ec", value: "ec", text: "Ecuador                    ", key: "ec" },
    { flag: "eg", value: "eg", text: "Egypt                      ", key: "eg" },
    { flag: "sv", value: "sv", text: "El Salvador                ", key: "sv" },
    { flag: "gq", value: "gq", text: "Equatorial Guinea          ", key: "gq" },
    { flag: "er", value: "er", text: "Eritrea                    ", key: "er" },
    { flag: "ee", value: "ee", text: "Estonia                    ", key: "ee" },
    { flag: "et", value: "et", text: "Ethiopia                   ", key: "et" },
    { flag: "eu", value: "eu", text: "Europeanunion              ", key: "eu" },
    { flag: "fk", value: "fk", text: "Falkland Islands           ", key: "fk" },
    { flag: "fo", value: "fo", text: "Faroe Islands              ", key: "fo" },
    { flag: "fj", value: "fj", text: "Fiji                       ", key: "fj" },
    { flag: "fi", value: "fi", text: "Finland                    ", key: "fi" },
    { flag: "fr", value: "fr", text: "France                     ", key: "fr" },
    { flag: "gf", value: "gf", text: "French Guinea-Bissau       ", key: "gf" },
    { flag: "pf", value: "pf", text: "French Polynesia           ", key: "pf" },
    { flag: "tf", value: "tf", text: "French Territories         ", key: "tf" },
    { flag: "ga", value: "ga", text: "Gabon                      ", key: "ga" },
    { flag: "gm", value: "gm", text: "Gambia                     ", key: "gm" },
    { flag: "ge", value: "ge", text: "Georgia                    ", key: "ge" },
    { flag: "de", value: "de", text: "Germany                    ", key: "de" },
    { flag: "gh", value: "gh", text: "Ghana                      ", key: "gh" },
    { flag: "gi", value: "gi", text: "Gibraltar                  ", key: "gi" },
    { flag: "gr", value: "gr", text: "Greece                     ", key: "gr" },
    { flag: "gl", value: "gl", text: "Greenland                  ", key: "gl" },
    { flag: "gd", value: "gd", text: "Grenada                    ", key: "gd" },
    { flag: "gp", value: "gp", text: "Guadeloupe                 ", key: "gp" },
    { flag: "gu", value: "gu", text: "Guam                       ", key: "gu" },
    { flag: "gt", value: "gt", text: "Guatemala                  ", key: "gt" },
    { flag: "gn", value: "gn", text: "Guinea                     ", key: "gn" },
    { flag: "gw", value: "gw", text: "Guinea-Bissau              ", key: "gw" },
    { flag: "gy", value: "gy", text: "Guyana                     ", key: "gy" },
    { flag: "ht", value: "ht", text: "Haiti                      ", key: "ht" },
    { flag: "hm", value: "hm", text: "Heard Island               ", key: "hm" },
    { flag: "hn", value: "hn", text: "Honduras                   ", key: "hn" },
    { flag: "hk", value: "hk", text: "Hong Kong                  ", key: "hk" },
    { flag: "hu", value: "hu", text: "Hungary                    ", key: "hu" },
    { flag: "is", value: "is", text: "Iceland                    ", key: "is" },
    { flag: "in", value: "in", text: "India                      ", key: "in" },
    { flag: "io", value: "io", text: "Indian Ocean Territory     ", key: "io" },
    { flag: "id", value: "id", text: "Indonesia                  ", key: "id" },
    { flag: "ir", value: "ir", text: "Iran                       ", key: "ir" },
    { flag: "iq", value: "iq", text: "Iraq                       ", key: "iq" },
    { flag: "ie", value: "ie", text: "Ireland                    ", key: "ie" },
    { flag: "il", value: "il", text: "Israel                     ", key: "il" },
    { flag: "it", value: "it", text: "Italy                      ", key: "it" },
    { flag: "jm", value: "jm", text: "Jamaica                    ", key: "jm" },
    {
      flag: "sj",
      value: "sj",
      text: "Jan Mayen                  ",
      key: "sj",
      alias: "Svalbard"
    },
    { flag: "jp", value: "jp", text: "Japan                      ", key: "jp" },
    { flag: "jo", value: "jo", text: "Jordan                     ", key: "jo" },
    { flag: "kz", value: "kz", text: "Kazakhstan                 ", key: "kz" },
    { flag: "ke", value: "ke", text: "Kenya                      ", key: "ke" },
    { flag: "ki", value: "ki", text: "Kiribati                   ", key: "ki" },
    { flag: "kw", value: "kw", text: "Kuwait                     ", key: "kw" },
    { flag: "kg", value: "kg", text: "Kyrgyzstan                 ", key: "kg" },
    { flag: "la", value: "la", text: "Laos                       ", key: "la" },
    { flag: "lv", value: "lv", text: "Latvia                     ", key: "lv" },
    { flag: "lb", value: "lb", text: "Lebanon                    ", key: "lb" },
    { flag: "ls", value: "ls", text: "Lesotho                    ", key: "ls" },
    { flag: "lr", value: "lr", text: "Liberia                    ", key: "lr" },
    { flag: "ly", value: "ly", text: "Libya                      ", key: "ly" },
    { flag: "li", value: "li", text: "Liechtenstein              ", key: "li" },
    { flag: "lt", value: "lt", text: "Lithuania                  ", key: "lt" },
    { flag: "lu", value: "lu", text: "Luxembourg                 ", key: "lu" },
    { flag: "mo", value: "mo", text: "Macau                      ", key: "mo" },
    { flag: "mk", value: "mk", text: "Macedonia                  ", key: "mk" },
    { flag: "mg", value: "mg", text: "Madagascar                 ", key: "mg" },
    { flag: "mw", value: "mw", text: "Malawi                     ", key: "mw" },
    { flag: "my", value: "my", text: "Malaysia                   ", key: "my" },
    { flag: "mv", value: "mv", text: "Maldives                   ", key: "mv" },
    { flag: "ml", value: "ml", text: "Mali                       ", key: "ml" },
    { flag: "mt", value: "mt", text: "Malta                      ", key: "mt" },
    { flag: "mh", value: "mh", text: "Marshall Islands           ", key: "mh" },
    { flag: "mq", value: "mq", text: "Martinique                 ", key: "mq" },
    { flag: "mr", value: "mr", text: "Mauritania                 ", key: "mr" },
    { flag: "mu", value: "mu", text: "Mauritius                  ", key: "mu" },
    { flag: "yt", value: "yt", text: "Mayotte                    ", key: "yt" },
    { flag: "mx", value: "mx", text: "Mexico                     ", key: "mx" },
    { flag: "fm", value: "fm", text: "Micronesia                 ", key: "fm" },
    { flag: "md", value: "md", text: "Moldova                    ", key: "md" },
    { flag: "mc", value: "mc", text: "Monaco                     ", key: "mc" },
    { flag: "mn", value: "mn", text: "Mongolia                   ", key: "mn" },
    { flag: "me", value: "me", text: "Montenegro                 ", key: "me" },
    { flag: "ms", value: "ms", text: "Montserrat                 ", key: "ms" },
    { flag: "ma", value: "ma", text: "Morocco                    ", key: "ma" },
    { flag: "mz", value: "mz", text: "Mozambique                 ", key: "mz" },
    { flag: "na", value: "na", text: "Namibia                    ", key: "na" },
    { flag: "nr", value: "nr", text: "Nauru                      ", key: "nr" },
    { flag: "np", value: "np", text: "Nepal                      ", key: "np" },
    { flag: "nl", value: "nl", text: "Netherlands                ", key: "nl" },
    { flag: "an", value: "an", text: "Netherlandsantilles        ", key: "an" },
    { flag: "nc", value: "nc", text: "New Caledonia              ", key: "nc" },
    { flag: "pg", value: "pg", text: "New Guinea                 ", key: "pg" },
    { flag: "nz", value: "nz", text: "New Zealand                ", key: "nz" },
    { flag: "ni", value: "ni", text: "Nicaragua                  ", key: "ni" },
    { flag: "ne", value: "ne", text: "Niger                      ", key: "ne" },
    { flag: "ng", value: "ng", text: "Nigeria                    ", key: "ng" },
    { flag: "nu", value: "nu", text: "Niue                       ", key: "nu" },
    { flag: "nf", value: "nf", text: "Norfolk Island             ", key: "nf" },
    { flag: "kp", value: "kp", text: "North Korea                ", key: "kp" },
    { flag: "mp", value: "mp", text: "Northern Mariana Islands   ", key: "mp" },
    { flag: "no", value: "no", text: "Norway                     ", key: "no" },
    { flag: "om", value: "om", text: "Oman                       ", key: "om" },
    { flag: "pk", value: "pk", text: "Pakistan                   ", key: "pk" },
    { flag: "pw", value: "pw", text: "Palau                      ", key: "pw" },
    { flag: "ps", value: "ps", text: "Palestine                  ", key: "ps" },
    { flag: "pa", value: "pa", text: "Panama                     ", key: "pa" },
    { flag: "py", value: "py", text: "Paraguay                   ", key: "py" },
    { flag: "pe", value: "pe", text: "Peru                       ", key: "pe" },
    { flag: "ph", value: "ph", text: "Philippines                ", key: "ph" },
    { flag: "pn", value: "pn", text: "Pitcairn Islands           ", key: "pn" },
    { flag: "pl", value: "pl", text: "Poland                     ", key: "pl" },
    { flag: "pt", value: "pt", text: "Portugal                   ", key: "pt" },
    { flag: "pr", value: "pr", text: "Puerto Rico                ", key: "pr" },
    { flag: "qa", value: "qa", text: "Qatar                      ", key: "qa" },
    { flag: "re", value: "re", text: "Reunion                    ", key: "re" },
    { flag: "ro", value: "ro", text: "Romania                    ", key: "ro" },
    { flag: "ru", value: "ru", text: "Russia                     ", key: "ru" },
    { flag: "rw", value: "rw", text: "Rwanda                     ", key: "rw" },
    { flag: "sh", value: "sh", text: "Saint Helena               ", key: "sh" },
    { flag: "kn", value: "kn", text: "Saint Kitts and Nevis      ", key: "kn" },
    { flag: "lc", value: "lc", text: "Saint Lucia                ", key: "lc" },
    { flag: "pm", value: "pm", text: "Saint Pierre               ", key: "pm" },
    { flag: "vc", value: "vc", text: "Saint Vincent              ", key: "vc" },
    { flag: "ws", value: "ws", text: "Samoa                      ", key: "ws" },
    { flag: "sm", value: "sm", text: "San Marino                 ", key: "sm" },
    { flag: "gs", value: "gs", text: "Sandwich Islands           ", key: "gs" },
    { flag: "st", value: "st", text: "Sao Tome                   ", key: "st" },
    { flag: "sa", value: "sa", text: "Saudi Arabia               ", key: "sa" },
    {
      flag: "gb",
      value: "gb",
      text: "Scotland                   ",
      key: "gb sct"
    },
    { flag: "sn", value: "sn", text: "Senegal                    ", key: "sn" },
    { flag: "cs", value: "cs", text: "Serbia                     ", key: "cs" },
    { flag: "rs", value: "rs", text: "Serbia                     ", key: "rs" },
    { flag: "sc", value: "sc", text: "Seychelles                 ", key: "sc" },
    { flag: "sl", value: "sl", text: "Sierra Leone               ", key: "sl" },
    { flag: "sg", value: "sg", text: "Singapore                  ", key: "sg" },
    { flag: "sk", value: "sk", text: "Slovakia                   ", key: "sk" },
    { flag: "si", value: "si", text: "Slovenia                   ", key: "si" },
    { flag: "sb", value: "sb", text: "Solomon Islands            ", key: "sb" },
    { flag: "so", value: "so", text: "Somalia                    ", key: "so" },
    { flag: "za", value: "za", text: "South Africa               ", key: "za" },
    { flag: "kr", value: "kr", text: "South Korea                ", key: "kr" },
    { flag: "es", value: "es", text: "Spain                      ", key: "es" },
    { flag: "lk", value: "lk", text: "Sri Lanka                  ", key: "lk" },
    { flag: "sd", value: "sd", text: "Sudan                      ", key: "sd" },
    { flag: "sr", value: "sr", text: "Suriname                   ", key: "sr" },
    { flag: "sz", value: "sz", text: "Swaziland                  ", key: "sz" },
    { flag: "se", value: "se", text: "Sweden                     ", key: "se" },
    { flag: "ch", value: "ch", text: "Switzerland                ", key: "ch" },
    { flag: "sy", value: "sy", text: "Syria                      ", key: "sy" },
    { flag: "tw", value: "tw", text: "Taiwan                     ", key: "tw" },
    { flag: "tj", value: "tj", text: "Tajikistan                 ", key: "tj" },
    { flag: "tz", value: "tz", text: "Tanzania                   ", key: "tz" },
    { flag: "th", value: "th", text: "Thailand                   ", key: "th" },
    { flag: "tl", value: "tl", text: "Timorleste                 ", key: "tl" },
    { flag: "tg", value: "tg", text: "Togo                       ", key: "tg" },
    { flag: "tk", value: "tk", text: "Tokelau                    ", key: "tk" },
    { flag: "to", value: "to", text: "Tonga                      ", key: "to" },
    { flag: "tt", value: "tt", text: "Trinidad                   ", key: "tt" },
    { flag: "tn", value: "tn", text: "Tunisia                    ", key: "tn" },
    { flag: "tr", value: "tr", text: "Turkey                     ", key: "tr" },
    { flag: "tm", value: "tm", text: "Turkmenistan               ", key: "tm" },
    { flag: "tv", value: "tv", text: "Tuvalu                     ", key: "tv" },
    {
      flag: "ae",
      value: "ae",
      text: "U.A.E.                     ",
      key: "ae",
      alias: "United Arab Emirates"
    },
    { flag: "ug", value: "ug", text: "Uganda                     ", key: "ug" },
    { flag: "ua", value: "ua", text: "Ukraine                    ", key: "ua" },
    {
      flag: "gb",
      value: "gb",
      text: "United Kingdom             ",
      key: "gb",
      alias: "uk"
    },
    {
      flag: "us",
      value: "us",
      text: "United States              ",
      key: "us",
      alias: "America"
    },
    { flag: "uy", value: "uy", text: "Uruguay                    ", key: "uy" },
    { flag: "um", value: "um", text: "US Minor Islands           ", key: "um" },
    { flag: "vi", value: "vi", text: "US Virgin Islands          ", key: "vi" },
    { flag: "uz", value: "uz", text: "Uzbekistan                 ", key: "uz" },
    { flag: "vu", value: "vu", text: "Vanuatu                    ", key: "vu" },
    { flag: "va", value: "va", text: "Vatican City               ", key: "va" },
    { flag: "ve", value: "ve", text: "Venezuela                  ", key: "ve" },
    { flag: "vn", value: "vn", text: "Vietnam                    ", key: "vn" },
    {
      flag: "gb",
      value: "gb",
      text: "Wales                      ",
      key: "gb wls"
    },
    { flag: "wf", value: "wf", text: "Wallis and Futuna          ", key: "wf" },
    { flag: "eh", value: "eh", text: "Western Sahara             ", key: "eh" },
    { flag: "ye", value: "ye", text: "Yemen                      ", key: "ye" },
    { flag: "zm", value: "zm", text: "Zambia                     ", key: "zm" },
    { flag: "zw", value: "zw", text: "Zimbabwe                   ", key: "zw" }
  ]
};
