export default {
  ters: {
    item1:
      "I declare that I am selling my bitcoin at the DLBTC rate, which will be attached to the automatic Ticket generated by this transaction, in accordance with the Terms established in this Terms and Conditions Agreement.\n",

    item2:
      "By performing this action of Sale, supply, add or select in my User Profile a bank account number owned by me or a third party, supplied and certified by me to receive payment for this Sale, which is included in my Profile, as Own or Third Party Account and will be linked to this Sale in accordance with this Terms and Conditions Agreement.\n",

    item3:
      "Once the data of the recipient account of the respective payment generated by the sale of my bitcoins is loaded, the system will generate an automatic transfer order to said account for the amount equivalent to the bitcoin sale made..\n",

    item4:
      "Said payment will be issued as soon as the operation is confirmed, for which I am aware that it is not a reversible operation nor can it be canceled once confirmed.\n",

    item5:
      "I declare to know the fees or any commission charged or debited by the receiving bank, which are not the responsibility of DLBTC and do not enter into the final calculation of the net amount paid.\n",

    item6:
      "Any collection of taxes, charges, fees for banking services or tax legislation applicable in the country where I receive the payment is the entire responsibility of the recipient, so DLBTC or its subsidiary local operators have no responsibility in the same. \n",

    item7:
      "The data of the destination account or receipt of payment are my entire responsibility and any error, omission or inconsistency in them, as well as the consequences of any of these errors or omissions will be my absolute responsibility.\n",

    item8:
      "In the event that you have mistakenly provided the erroneous data of the destination account and the sales transaction has been confirmed, DLBTC will not be responsible for the payment issued.\n",

    item9:
      "Under no circumstances may the payment be retracted or invalidated since DLBTC indexes payments from certified accounts of its operators to make the purchase and sale between two parties, and does not use its own accounts to make bank payments of any kind.\n",

    item10:
      "If due to an inadvertent error in supplying the data of the receiving account, the respective payment can not be processed, a member of the arbitration team of DLBTC.com will contact you to request that you correct the information in your User Profile, a Once corrected, the corresponding payment will be made.\n",

    item11:
      "Any delay caused by this or these errors will not be the responsibility of DLBTC.com.\n",

    item12:
      "Once the Transaction is confirmed, the system will give an approximate lapse in which the Payment will be made, a corresponding support will also be sent to your message box, in which will be the net amount, the date, time of the payment made and the Ticket number in the payment concept.\n",

    item13:
      "If for some reason the corresponding payment has delays in being available, and the reason, for any reason, is caused by the internal processes of the banks, or the countries where the payment was made, (such as holidays, delays in the bank validation, or any other case), DLBTC will have no responsibility for such delay or be liable for any damage or injury caused by such delay.\n",

    item14:
      "If instead there is a delay of more than six (6) continuous hours in the ISSUANCE of the payment, it will proceed to the Cancellation of the Sale in the case that is required, being able to make the Sale again at the current rate in the moment to reactivate the Sale.\n",

    item15:
      " In this case DLBTC is not responsible for any problem, damage or injury that this may cause.\n",

    item16:
      "This Sale procedure is done by my own will, I declare under oath that the funds obtained will not be used for illicit purposes, for financing or promotion of terrorist activities, for tax evasion nor will I use the technological benefits of using this platform to launder money, legitimize capital or evade sanctions or taxes of any kind, I also declare that I know and abide by the current legislation of my country of residence with respect to the purchase and sale of cryptocurrencies.\n"
  }
};
